<a href="https://colab.research.google.com/github/sreejithlal592-bit/numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
  import numpy as np #numericak python
#array
a=np.array([1,2,3.9,4,"a"])
print(a)

['1' '2' '3.9' '4' 'a']


In [ ]:
b=np.array([1,2,3,4,5])
print(b[0:2])
print(b[-1:-3:-1])
print(b[3:])
print(b[-4::-1])

[1 2]
[5 4]
[4 5]
[2 1]


In [ ]:
#dimension
a=np.array([0,2,3,4,5])
b=np.array([[1,3,2],[3,4,4],[2,4,4]])
a.ndim
b.ndim
print(b)
b.shape

[[1 3 2]
 [3 4 4]
 [2 4 4]]


(3, 3)

In [ ]:
#create a 2x2 metrix

In [ ]:
a=np.array([[2,3],[4,5]])

print(a)
print(a.shape)#to check shape of metix
print(a.ndim)
print(a.size)#to check size/total elements in metrix

[[2 3]
 [4 5]]
(2, 2)
2
4


In [ ]:
#2x3 matrix

In [ ]:
y=np.array([[2,4,3],[3,5,5],])
print(y)
print(y.size)
print(y.ndim)
print(y.shape)

[[2 4 3]
 [3 5 5]
 [2 3 4]]
9
2
(3, 3)


In [ ]:
m=np.array([[2,3],[4,3],[3,4],[5,5]])
print(m)
print(m.size)
print(m.ndim)
print(m.shape)

[[2 3]
 [4 3]
 [3 4]
 [5 5]]
8
2
(4, 2)


In [ ]:
import numpy as np
m=np.array([[2,8,9,3],[4,1,7,3],[3,9,0,4],[5,1,5,5]])
print(m)
print(m.size)
print(m.ndim)
print(m.shape)


SyntaxError: invalid syntax (ipython-input-2125328865.py, line 7)

In [ ]:
z=np.array([[0,1,2,3],[2,9,3,4],[3,8,5,6],[2,1,5,7]])
print(z)
print(z[0])
print(z[:,0])
print(z[3,2:])
print(z[2:,2:])
print(z[1:3,3])
print(z[1:3,0:3])

[[0 1 2 3]
 [2 9 3 4]
 [3 8 5 6]
 [2 1 5 7]]
[0 1 2 3]
[0 2 3 2]
[5 7]
[[5 6]
 [5 7]]
[4 6]
[[2 9 3]
 [3 8 5]]


In [ ]:
#zero metrix
z=np.zeros([2,3,3],dtype=int)
print(z)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [ ]:
z=np.ones([3,3],dtype=int)
print(z)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
#cret two 2x2 metrix
a=np.array([[2,3],[3,4]])
b=np.array([[5,2],[9,4]])
b.shape
print(a)
print(b)
#metrix addition
print(a+b)
#metrix sub
print(a-b)
#metrix multiplication
print(a*b)#not matrix multipilcation
print(a@b)#matrix multiplication
print(a.dot(b))#matrix multiplication
#metrix division
print(a/b)
#"magic"= starting with undercores eg __add__



[[2 3]
 [3 4]]
[[5 2]
 [9 4]]
[[ 7  5]
 [12  8]]
[[-3  1]
 [-6  0]]
[[10  6]
 [27 16]]
[[37 16]
 [51 22]]
[[37 16]
 [51 22]]
[[0.4        1.5       ]
 [0.33333333 1.        ]]


In [ ]:
#full matrix
z=np.full([3,3],5,dtype=int)
print(z)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [ ]:
#create a 3x3 metriz with value 9 with complex data type
z=np.full([3,4],9,dtype=complex)
print(z)


[[9.+0.j 9.+0.j 9.+0.j 9.+0.j]
 [9.+0.j 9.+0.j 9.+0.j 9.+0.j]
 [9.+0.j 9.+0.j 9.+0.j 9.+0.j]]


In [ ]:
#identity metrix
z=np.identity(3,dtype=int)#method 1 to identity metrix
print(z)

z=np.eye(3)#method 2 to identity metrix
z

[[1 0 0]
 [0 1 0]
 [0 0 1]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
m=np.array([[2,2,2,2],[3,3,3,3],[4,4,4,4],[5,5,5,5]])
print(m)
print(m.size)
a=m.reshape(4,4)
print(a)

[[2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]]
16
[[2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]]


In [ ]:
#arange
a=np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [ ]:
k=np.arange(1,11)
a=k.reshape(5,2)
print(a)
print(k)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
a=np.array([[2.5,3.6,3.5],[1.5,1.8,2.9],[1.4,1.6,1.1]])
print(a)
z=np.floor(a)#floor
z
#ceil
h=np.ceil(a)
h
#round
n=np.round(a)
n

[[2.5 3.6 3.5]
 [1.5 1.8 2.9]
 [1.4 1.6 1.1]]


array([[2., 4., 4.],
       [2., 2., 3.],
       [1., 2., 1.]])

In [ ]:
import numpy as np
a=np.arange(1,10).reshape(3,3)
print(a)
a.max()
a.max(axis=0)
a.sum(axis=0)#sum of columns
a.sum(axis=1)#sum of rows
print(np.sqrt(a))#to get squareroot of each elements in the metrix
print(np.sin(a))#to find sin values of elemments in the metrix
print(np.tan(a))#to find tan values of elements in the metrix
#flatten
a.flatten()# flaten is used to make any dimensional arraay to single/one dimensional


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -6.79971146 -0.45231566]]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#sort
#create a 3x3 metrix
a=np.array([[11,34,22],[5,3,1],[9,2,4]])
print(a)
b=np.sort(a,axis=1)
print(b)
c=np.argsort(a,axis=1)
print(c)
a.flatten()

[[11 34 22]
 [ 5  3  1]
 [ 9  2  4]]
[[11 22 34]
 [ 1  3  5]
 [ 2  4  9]]
[[0 2 1]
 [2 1 0]
 [1 2 0]]


array([11, 34, 22,  5,  3,  1,  9,  2,  4])